#B:\mytestProjects\JavaPROJECTS\TaskMngtAppBackend\taskmgtappv1\src\main\resources\application.yml
# Server configuration
server:
  port: 8080
  # Increase max header size to 32KB (adjust as needed)
  max-http-request-header-size: 32KB

# Spring Boot Configuration
spring:
  # === SQL SERVER DATASOURCE CONFIGURATION ===
  datasource:
    # FIXED: Corrected URL format and removed duplicate credentials
    url: jdbc:sqlserver://localhost:1433;databaseName=TaskMgtJavaDB;encrypt=false;trustServerCertificate=true
    # Credentials specified here (not in URL)
    username: Admin1
    password: Mulu@2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  # === FLYWAY MIGRATION CONFIGURATION ===
  flyway:
    enabled: true
    locations: classpath:db/migration
    # Flyway will use the same datasource credentials automatically
    # No need to specify user, password, and url separately unless different
    
  # === JPA (HIBERNATE) CONFIGURATION ===
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

# Swagger/OpenAPI Documentation configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    
# Logging configuration
logging:
  level:
    root: INFO
    com.taskmanagementbackend.taskmgtappv1: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.flywaydb: DEBUG  # To see Flyway migration logs