# Server configuration
server:
  port: 8080

# Spring Boot Configuration
spring:
  # === SQL SERVER DATASOURCE CONFIGURATION ===
  datasource:
    # CHANGED: Removed integratedSecurity=true and added encrypt=true for better security
    url: jdbc:sqlserver://Admin1\\SQLEXPRESS;databaseName=TaskMgtJavaDB;encrypt=true;trustServerCertificate=true
    # ADD: Your SQL Server credentials
    username: Admin1 #your_sql_username
    password: Mulu@2025 #your_sql_password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  # === FLYWAY MIGRATION CONFIGURATION ===
  flyway:
    enabled: true
    locations: classpath:db/migration
    # ADD: Flyway needs the same credentials
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    
  # === JPA (HIBERNATE) CONFIGURATION ===
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

# Swagger/OpenAPI Documentation configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    
# Logging configuration
logging:
  level:
    root: INFO
    com.taskmanagementbackend.taskmgtappv1: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.flywaydb: DEBUG  # ADD: To see Flyway migration logs